# Generated by Django 5.0 on 2024-01-01 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name="pet",
            name="age",
        ),
        migrations.AddField(
            model_name="pet",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="birth_date"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=40, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="pet",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pet",
                to="pet.race",
                verbose_name="race",
            ),
        ),
    ]
