# Generated by Django 5.0 on 2024-01-01 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_race_remove_pet_age_pet_birthday_alter_pet_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Race",
            new_name="Breed",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="race",
        ),
        migrations.AddField(
            model_name="pet",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pet",
                to="pet.breed",
                verbose_name="breed",
            ),
        ),
    ]
