# Generated by Django 5.0 on 2024-01-01 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_person_birthday_alter_person_phone_number_and_more"),
        ("pet", "0003_rename_race_breed_remove_pet_race_pet_breed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pets",
                to="pet.breed",
                verbose_name="breed",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pets",
                to="people.person",
            ),
        ),
    ]
