# Generated by Django 5.0 on 2024-01-01 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_person_birthday_alter_person_phone_number_and_more"),
        ("pet", "0005_alter_pet_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pets",
                to="people.person",
                verbose_name="owner",
            ),
        ),
    ]
