# Generated by Django 5.0.2 on 2024-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, help_text='Max size allowed: 20Mbs', null=True, upload_to='pet/', verbose_name='picture'),
        ),
    ]
