# Generated by Django 5.0 on 2024-01-01 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactWay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "contact way",
                "verbose_name_plural": "contact ways",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "occupation",
                "verbose_name_plural": "occupations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[("DNI", "Identity Card"), ("Passport", "Passport")],
                        default="DNI",
                        max_length=30,
                        null=True,
                        verbose_name="document type",
                    ),
                ),
                (
                    "document_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="document id",
                    ),
                ),
                (
                    "educational_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primary", "Primary school"),
                            ("Secondary", "Secondary school"),
                            ("Tertiary", "Tertiary"),
                            ("University", "University"),
                            ("Postgraduate", "Postgraduate"),
                            ("TBC", "To be confirmed"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="educational level",
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="personal email",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="+54 11 11111111 (spaces are optional)",
                        max_length=255,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "secondary_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="+54 11 11111111 (spaces are optional)",
                        max_length=255,
                        null=True,
                        verbose_name="secondary phone number",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="address"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="neighborhood"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Female"), ("M", "Male")],
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Max size allowed: 20Mbs",
                        null=True,
                        upload_to="people_images/",
                        verbose_name="picture",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="structure.city",
                        verbose_name="city",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.country",
                        verbose_name="nationality",
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person",
                        to="people.occupation",
                        verbose_name="occupation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "People",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("nationality", "document_type", "document_id"),
                name="people_person_unique_nationality_document_type_and_id",
            ),
        ),
    ]
